#!/usr/bin/python3
"""A models that inherits base from base"""
from models.base import Base


class Rectangle(Base):
    """
    Class rectangle that inherits from base
    """

    @property
    def __width(self):
        return self.width

    @width.setter
    def __width(self, value):
        self.width = value

    @property
    def __height(self):
        return self.height

    @height.setter
    def __height(self, value):
        self.height = value

    @property
    def __x(self):
        return self.x

    @x.setter
    def __x(self, value):
        self.x = value

    @property
    def __y(self):
        return self.y

    @y.setter
    def __y(self, value):
        self.y = value

    def __init__(self, width, height, x=0, y=0, id=None):
        super().__init__(id)
        self.width = width
        self.height = height
        self.x = x
        self.y = y
